export const SELECT_CITY = "SELECT_CITY"
export const FETCH_WEATHER_START = "FETCH_WEATHER_DATA_START"
export const FETCH_WEATHER_OK = "FETCH_WEATHER_DATA_OK"
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_DATA_ERROR"